/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import laporan.LaporanDataKriteria;
import laporan.LaporanDataPemilihan;
import laporan.LaporanDataPemilikToko;



/**
 *
 * @author afgha
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPemilikToko = new javax.swing.JButton();
        bDataKriteria = new javax.swing.JButton();
        bDataPemilihan = new javax.swing.JButton();
        bDataPerbandingan = new javax.swing.JButton();
        bDataRanking = new javax.swing.JButton();
        bDataInterview = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bLaporanDataPemilikToko = new javax.swing.JButton();
        bLaporanDataKriteria = new javax.swing.JButton();
        bLaporanDataPemilihan = new javax.swing.JButton();
        bLaporanDataInterview = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bPemilikToko.setText("Data Pemilik Toko");
        bPemilikToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPemilikTokoActionPerformed(evt);
            }
        });

        bDataKriteria.setText("Data Kriteria");
        bDataKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataKriteriaActionPerformed(evt);
            }
        });

        bDataPemilihan.setText("Data Pemilihan");
        bDataPemilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataPemilihanActionPerformed(evt);
            }
        });

        bDataPerbandingan.setText("Data Perbandingan");
        bDataPerbandingan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataPerbandinganActionPerformed(evt);
            }
        });

        bDataRanking.setText("Data Ranking");
        bDataRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataRankingActionPerformed(evt);
            }
        });

        bDataInterview.setText("Data Interview");
        bDataInterview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataInterviewActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SEBAGAI PENDUKUNG  MENENTUKAN KUALITAS PLASTIK PADA TOKO PLASTIK BENGKIT ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IMPLEMENTASI METODE ANALYTICAL HIERARCHY PROCESS (AHP) ");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" KP. Padurenan RT 02/RW 01 Kel. Pabuaran Kec. Cibinong , Kab. Bogor 16916.");

        bLaporanDataPemilikToko.setText("Laporan Data Pemilik Toko");
        bLaporanDataPemilikToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaporanDataPemilikTokoActionPerformed(evt);
            }
        });

        bLaporanDataKriteria.setText("Laporan Data Kriteria");
        bLaporanDataKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaporanDataKriteriaActionPerformed(evt);
            }
        });

        bLaporanDataPemilihan.setText("Laporan Data Pemilihan");
        bLaporanDataPemilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaporanDataPemilihanActionPerformed(evt);
            }
        });

        bLaporanDataInterview.setText("Laporan Data Interview");
        bLaporanDataInterview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaporanDataInterviewActionPerformed(evt);
            }
        });

        bKeluar.setBackground(new java.awt.Color(255, 51, 51));
        bKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bPemilikToko, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bDataKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bDataPemilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bDataPerbandingan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bDataRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bDataInterview, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(bLaporanDataPemilikToko)
                .addGap(18, 18, 18)
                .addComponent(bLaporanDataKriteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLaporanDataPemilihan)
                .addGap(18, 18, 18)
                .addComponent(bLaporanDataInterview)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(355, 355, 355))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bKeluar)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPemilikToko, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataPemilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataPerbandingan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataInterview, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLaporanDataPemilikToko, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLaporanDataKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLaporanDataPemilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLaporanDataInterview, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDataPemilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataPemilihanActionPerformed
       DataPemilihan dp = new DataPemilihan();
       dp.setVisible(true);
    }//GEN-LAST:event_bDataPemilihanActionPerformed

    private void bDataPerbandinganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataPerbandinganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDataPerbandinganActionPerformed

    private void bDataRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataRankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDataRankingActionPerformed

    private void bDataInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataInterviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDataInterviewActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bPemilikTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPemilikTokoActionPerformed
       DataPemilikToko dpt = new DataPemilikToko();
       dpt.setVisible(true);
    }//GEN-LAST:event_bPemilikTokoActionPerformed

    private void bDataKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataKriteriaActionPerformed
       DataKriteria dk = new DataKriteria();
       dk.setVisible(true);
    }//GEN-LAST:event_bDataKriteriaActionPerformed

    private void bLaporanDataPemilikTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanDataPemilikTokoActionPerformed
        LaporanDataPemilikToko ldpk = new LaporanDataPemilikToko();
        ldpk.setVisible(true);
    }//GEN-LAST:event_bLaporanDataPemilikTokoActionPerformed

    private void bLaporanDataKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanDataKriteriaActionPerformed
        LaporanDataKriteria ldk = new LaporanDataKriteria();
        ldk.setVisible(true);
    }//GEN-LAST:event_bLaporanDataKriteriaActionPerformed

    private void bLaporanDataPemilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanDataPemilihanActionPerformed
        LaporanDataPemilihan ldp = new LaporanDataPemilihan();
        ldp.setVisible(true);
    }//GEN-LAST:event_bLaporanDataPemilihanActionPerformed

    private void bLaporanDataInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanDataInterviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLaporanDataInterviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDataInterview;
    private javax.swing.JButton bDataKriteria;
    private javax.swing.JButton bDataPemilihan;
    private javax.swing.JButton bDataPerbandingan;
    private javax.swing.JButton bDataRanking;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bLaporanDataInterview;
    private javax.swing.JButton bLaporanDataKriteria;
    private javax.swing.JButton bLaporanDataPemilihan;
    private javax.swing.JButton bLaporanDataPemilikToko;
    private javax.swing.JButton bPemilikToko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
